sudo: required
language: go

go:
  - 1.x

services:
  - mysql
  - postgresql

env:
  - TEST_POSTGRES="postgres://postgres@localhost:5432?sslmode=disable"
    TEST_MYSQL="root@tcp(localhost:3306)/"

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/go-playground/overalls
  - make deps

script:
  - make test
  - $GOPATH/bin/overalls -project=github.com/hellofresh/klepto -covermode=count
  - if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ]; then bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile; fi

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
